---
- name: nodejs install script download
  shell: curl -sL https://deb.nodesource.com/setup_7.x -o nodesource_setup.sh
  sudo: no

- name: nodejs setup execution
  shell: bash nodesource_setup.sh

- name: nodejs install
  apt:
    name: nodejs
    state: present
    update_cache: yes

